name: Build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: On macOS a development/trunk toolchain is needed until
        # https://github.com/apple/swift-package-manager/pull/6772 is included
        # in a release.
        os: ['ubuntu-latest']
        swift: ['5.9']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libtinyxml2-dev libcairomm-1.16-1 libpangomm-2.48-1 libfontconfig1-dev
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install tinyxml2 cairomm pangomm fontconfig
    - name: Build
      run: swift build
