name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        # TODO: A Ubuntu Docker image is needed until 24.04 LTS is supported
        # natively in GitHub runners since the newer versions of cairomm
        # and pangomm are required
        # TODO: A development/trunk toolchain is needed until
        # - https://github.com/apple/swift-package-manager/pull/6772
        # - https://github.com/apple/swift-package-manager/pull/7232
        # are included in a release.
        os: ['macos-14']
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libtinyxml2-dev libcairomm-1.16-dev libpangomm-2.48-dev libfontconfig1-dev
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install tinyxml2 cairomm pangomm fontconfig
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: 'swift-DEVELOPMENT-SNAPSHOT-2024-02-12-a'
        development: true
        check-latest: true
    - name: Build
      run: swift build
